---
title: "Thesis: Sensitivity Analysis"
author: "R-Walmsley"
date: "2022-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Note location of input files
```{r}
input_loc <- "../../../../paperRW2021/"
```

# Load packages
```{r}
lapply(c("ggplot2", "survival", "table1", "epicoda", "EValue"), library, character.only = TRUE) # Note version of epicoda: devtools::install_github("activityMonitoring/epicoda", ref = "fedd06114d664cfcd4087e6620b672e111f37ef0")
source("../../useful_functions/round_2_dp.R")
source("../../useful_functions/consistent_theme.R")
```

# Load data 
```{r}
name_of_current_run <- "2022-01-20update_negative_control" # use data from the most recent run
df <-  readRDS(paste0(input_loc, 
   "/epiAnalysis/inputData/",
   name_of_current_run,
   "_ready_to_use.RDS"
 ))

df_only_fu <-
  readRDS(paste0(input_loc, 
    "epiAnalysis/inputData/",
    name_of_current_run,
    "_only_fu.RDS"
  ))
df_sensitivity <-
  readRDS(paste0(input_loc, 
    "epiAnalysis/inputData/",
    name_of_current_run,
    "_sensitivity.RDS"
  ))
```

# Also identify healthy and unhealthy subsets
```{r}
df_healthy <- df[!(df$meds|df$poor_health|(df$any_previous_I_code ==1)), ]
df_unhealthy <- df[(df$meds|df$poor_health|(df$any_previous_I_code ==1)), ]

if (nrow(df_healthy) + nrow(df_unhealthy) != nrow(df)){
  stop("Error in identification of subsets")
}
```

# Set up 
```{r}
# Comp labels
comp_labels <-
  c("sleep", "SB", "LIPA", "MVPA")
tl <-
  transf_labels(comp_labels,
                transformation_type = "ilr")

# List of covariates except sex and bmi
covs <-
  c(
    "ethnicity",
    "smoking",
    "alcohol",
    "fruit_and_veg_cats",
    "red_and_processed_meat_cats",
    "oily_fish",
    "TDI_quartiles",
    "education_cats"
  )

# List of covariates for descriptive tables
covs_cat <- c('age_cats', 'sex', covs, 'BMI_cats')

# Negative control dataset 
df_nc <- df[df$accidents_new.prevalent == 0, ]
```

# Modelling
```{r}
rot_list <- list(
  "sleep" = c("sleep", "SB", "LIPA", "MVPA"),
  "SB" = c("SB", "sleep", "LIPA", "MVPA"),
  "LIPA" = c("LIPA", "sleep", "SB",  "MVPA"),
  "MVPA" = c("MVPA", "sleep", "SB", "LIPA")
)

cm <- epicoda::comp_mean(df, rot_list[[1]])

# Calculate models =========================================================
rec_dat_sensitivity <- data.frame(matrix(nrow = 8, ncol = 6))
colnames(rec_dat_sensitivity) <-
  c("Behaviour",
    "Difference",
    "Model",
    "HR",
    "LowerCI",
    "UpperCI")

rec_dat_nc <- data.frame(matrix(nrow = 8, ncol = 6))
colnames(rec_dat_nc) <-
  c("Behaviour",
    "Difference",
    "Model",
    "HR",
    "LowerCI",
    "UpperCI")

rec_dat_hu <- data.frame(matrix(nrow = 12, ncol = 6))
colnames(rec_dat_hu) <-
  c("Behaviour",
    "Difference",
    "Model",
    "HR",
    "LowerCI",
    "UpperCI")

for (i in 1:length(rot_list)) {
  # Basic set up ------------------------------------------------------------------------
  comp_labels <- rot_list[[i]]
  comp_name <- names(rot_list)[i]

  # Set up ref values for later looking at transformation --------------------------------
  if (comp_name == "MVPA") {
    diff <- 1 / (24 * 3)
  } else {
    diff <- 1 / 24
  }
  pivvar <- cm[, comp_name]
  pivvarnew <- pivvar + diff

  othvarname <- colnames(cm)[colnames(cm) != comp_name]
  othvar <- cm[, othvarname]
  othvarnew <- othvar
  for (var in othvarname) {
    othvarnew[, var] <-
      othvar[, var] - diff * othvar[, var] / sum(othvar)
  }

  ilr_old <-
    sqrt(3 / 4) * log(pivvar / (othvar[, 1] * othvar[, 2] * othvar[, 3]) ^
                        (1 / 3))
  ilr_new <-
    sqrt(3 / 4) * log(pivvarnew / (othvarnew[, 1] * othvarnew[, 2] * othvarnew[, 3]) ^
                        (1 / 3))
  ilr_diff <- ilr_new - ilr_old

  # do main model -----------------------------------------------------------
  main_model <-
  comp_model(
    type = "cox",
    covariates = c("strata(sex)", covs),
    outcome = Surv(
      time = df$age_entry,
      time2 = df$age_exit,
      event = df$CVD_event
    ),
    data = df,
    comp_labels = comp_labels,
    rounded_zeroes = TRUE
  )
  rnames <- rownames(summary(main_model)$conf.int)
  rid <- rnames[grepl("ilr_1", rnames)]
  vals <- summary(main_model)$conf.int[rid, c(1, 3, 4)]
  HRs <- vals ^ ilr_diff
  
  rec_dat_sensitivity[(i - 1) * 2 + 1,] <- c(comp_name, diff, "main analysis", HRs)
  rec_dat_nc[(i-1)*2 + 1, ] <-  c(comp_name, diff, "main analysis", HRs)
  rec_dat_hu[(i - 1) * 3 + 1,] <- c(comp_name, diff, "main analysis", HRs)
  
  ## Sensitivity analyses for reverse causation----------------------------
  only_fu_model <-
  comp_model(
    type = "cox",
    covariates = c("strata(sex)", covs),
    outcome = Surv(
      time = df_only_fu$age_entry,
      time2 = df_only_fu$age_exit,
      event = df_only_fu$CVD_event
    ),
    data = df_only_fu,
    comp_labels = comp_labels,
    rounded_zeroes = TRUE
  )
  vals <- summary(only_fu_model)$conf.int[rid, c(1, 3, 4)]
  HRs <- vals ^ ilr_diff
  rec_dat_sensitivity[(i - 1) * 2 + 2,] <- c(comp_name, diff, "first 2 years follow-up removed", HRs)
  
  # main_sensitivity_model <-
  # comp_model(
  #   type = "cox",
  #   covariates = c("strata(sex)", covs),
  #   outcome = Surv(
  #     time = df_sensitivity$age_entry,
  #     time2 = df_sensitivity$age_exit,
  #     event = df_sensitivity$CVD_event
  # 
  #   ),
  #   data = df_sensitivity,
  #   comp_labels = comp_labels,
  #   rounded_zeroes = TRUE
  # )
  # 
  # vals <- summary(main_sensitivity_model)$conf.int[rid, c(1, 3, 4)]
  # HRs <- vals ^ ilr_diff
  # rec_dat_sensitivity[(i - 1) * 3 + 3,] <- c(comp_name, diff, "first 2 years follow-up removed + healthy subcohort", HRs)
  
  
  ## Negative control model -------------------------------------------------
  neg_control_model <-
    comp_model(
    type = "cox",
    covariates = c("strata(sex)", covs) ,
    outcome = Surv(
      time = df_nc$age_entry,
      time2 = df_nc$neg_control_acc_exit,
      event = df_nc$neg_control_event_acc
    ),
    data = df_nc,
    comp_labels = comp_labels,
    rounded_zeroes = TRUE
  )
  vals <- summary(neg_control_model)$conf.int[rid, c(1, 3, 4)]
  HRs <- vals ^ ilr_diff
  rec_dat_nc[(i - 1) * 2 + 2,] <- c(comp_name, diff, "negative control", HRs)
  
  
  
  ## Healthy model -------------------------------------------------
  healthy_model <-
    comp_model(
    type = "cox",
    covariates = c("strata(sex)", covs) ,
    outcome = Surv(
      time = df_healthy$age_entry,
      time2 = df_healthy$age_exit,
      event = df_healthy$CVD_event
    ),
    data = df_healthy,
    comp_labels = comp_labels,
    rounded_zeroes = TRUE
  )
  vals <- summary(healthy_model)$conf.int[rid, c(1, 3, 4)]
  HRs <- vals ^ ilr_diff
  rec_dat_hu[(i - 1) * 3 + 2,] <- c(comp_name, diff, "healthy", HRs)
  
  ## Unhealthy model -------------------------------------------------
  unhealthy_model <-
    comp_model(
    type = "cox",
    covariates = c("strata(sex)", covs) ,
    outcome = Surv(
      time = df_unhealthy$age_entry,
      time2 = df_unhealthy$age_exit,
      event = df_unhealthy$CVD_event
    ),
    data = df_unhealthy,
    comp_labels = comp_labels,
    rounded_zeroes = TRUE
  )
  vals <- summary(unhealthy_model)$conf.int[rid, c(1, 3, 4)]
  HRs <- vals ^ ilr_diff
  rec_dat_hu[(i - 1) * 3 + 3,] <- c(comp_name, diff, "unhealthy", HRs)
  
  
  
  
}
```


Admin: 
```{r}
for (var in c("HR", "LowerCI", "UpperCI")) {
  rec_dat_sensitivity[, var] <- as.numeric(rec_dat_sensitivity[, var])
  rec_dat_nc[, var] <- as.numeric(rec_dat_nc[, var])
  rec_dat_hu[, var] <- as.numeric(rec_dat_hu[, var])
}

rdcs <- rec_dat_sensitivity # This just saves the df so it's not a pain to get back if needed
rdcn <- rec_dat_nc # This just saves the df so it's not a pain to get back if needed
rdch <- rec_dat_hu  # This just saves the df so it's not a pain to get back if needed
```

# Forest plot - reverse causality

Admin: 
```{r}
### This part is admin for labels etc --------------------------------------------
rec_dat_sensitivity$label <-
  paste0(
    round_2_dp(rec_dat_sensitivity$HR),
    " (",
    round_2_dp(rec_dat_sensitivity$LowerCI),
    ", ",
    round_2_dp(rec_dat_sensitivity$UpperCI),
    ")"
  )

rec_dat_sensitivity$Behaviour <-
  factor(rec_dat_sensitivity$Behaviour, ordered = TRUE, levels = rot_list[[1]])
rec_dat_sensitivity$BehaviourDet <- plyr::revalue(
  rec_dat_sensitivity$Behaviour,
  c(
    "MVPA" = "MVPA (extra 20 min/day)",
    "LIPA" = "LIPA (extra 1 hr/day)",
    "SB" = "SB (extra 1 hr/day)",
    "sleep" = "Sleep (extra 1 hr/day)"
  )
)

rec_dat_sensitivity$Model <-
  factor(rec_dat_sensitivity$Model,
         ordered = TRUE,
         c( "first 2 years follow-up removed", "main analysis"))


my_cols <- c( "darkred", "black")
```

Plotting: 
```{r}
p <- # DATA AND AESTHETICS
  ggplot(data = rec_dat_sensitivity,
            aes(
              x = HR,
              y = BehaviourDet ,
              colour= Model,
              group = Model,
              label = label
            )) +
  # GEOMS
  geom_pointrange(position = position_dodge(0.6), aes(xmin = LowerCI, xmax = UpperCI), size = 1, shape = 18) +
  geom_text(
    size = 4.5,
    aes(x = 1.18, y = BehaviourDet, label = label),
    position = position_dodge(0.6),
    colour = "black", 
    fontface = "bold"
  ) +
  geom_vline(xintercept = 1, size = 0.75) +

  # SCALES
  scale_x_continuous(trans = "log10", breaks = c(0.9, 0.95, 1, 1.05)) +
  scale_color_manual(values = my_cols, guide = guide_legend(reverse = TRUE)) +
 # scale_shape_manual(values = c(18, 20), guide = "none" ) +
 
  # CONSISTENT THEME 
  consistent_theme

## save plot to file----------------------------------------------------------------------------------------------
svg(
  "plots/thesis-sensitivity.svg",
  width = 10,
  height = 5
)
print(p)
dev.off()
```


# Forest plot - negative control

Admin: 
```{r}
### This part is admin for labels etc --------------------------------------------
rec_dat_nc$label <-
  paste0(
    round_2_dp(rec_dat_nc$HR),
    " (",
    round_2_dp(rec_dat_nc$LowerCI),
    ", ",
    round_2_dp(rec_dat_nc$UpperCI),
    ")"
  )

rec_dat_nc$Behaviour <-
  factor(rec_dat_nc$Behaviour, ordered = TRUE, levels = rot_list[[1]])
rec_dat_nc$BehaviourDet <- plyr::revalue(
  rec_dat_nc$Behaviour,
  c(
    "MVPA" = "MVPA (extra 20 min/day)",
    "LIPA" = "LIPA (extra 1 hr/day)",
    "SB" = "SB (extra 1 hr/day)",
    "sleep" = "Sleep (extra 1 hr/day)"
  )
)

rec_dat_nc$Model <-
  factor(rec_dat_nc$Model,
         ordered = TRUE,
         c("negative control", "main analysis"))


my_cols <- c("darkred", "black")
```

Plotting:
```{r}
p <- # DATA AND AESTHETICS
  ggplot(data = rec_dat_nc,
            aes(
              x = HR,
              y = BehaviourDet ,
              colour= Model,
              group = Model,
              label = label
            )) +
  # GEOMS
  geom_pointrange(position = position_dodge(0.6), aes(xmin = LowerCI, xmax = UpperCI), size = 1, shape = 18) +
  geom_text(
    size = 4.5,
    aes(x = 1.18, y = BehaviourDet, label = label),
    position = position_dodge(0.6),
    colour = "black", 
    fontface = "bold"
  ) +
  geom_vline(xintercept = 1, size = 0.75) +
  
  # SCALES
  scale_x_continuous(trans = "log10", breaks = c(0.9, 0.95, 1, 1.05)) +
  scale_color_manual(values = my_cols, guide = guide_legend(reverse = TRUE)) +
 # scale_shape_manual(values = c(18, 20), guide = "none" ) +

  # CONSISTENT THEME
  consistent_theme

## save plot to file----------------------------------------------------------------------------------------------
svg(
  "plots/thesis-nc.svg",
  width = 10,
  height = 5
)
print(p)
dev.off()
```


# Forest plot - reverse causality

Admin: 
```{r}
### This part is admin for labels etc --------------------------------------------
rec_dat_hu$label <-
  paste0(
    round_2_dp(rec_dat_hu$HR),
    " (",
    round_2_dp(rec_dat_hu$LowerCI),
    ", ",
    round_2_dp(rec_dat_hu$UpperCI),
    ")"
  )

rec_dat_hu$Behaviour <-
  factor(rec_dat_hu$Behaviour, ordered = TRUE, levels = rot_list[[1]])
rec_dat_hu$BehaviourDet <- plyr::revalue(
  rec_dat_hu$Behaviour,
  c(
    "MVPA" = "MVPA (extra 20 min/day)",
    "LIPA" = "LIPA (extra 1 hr/day)",
    "SB" = "SB (extra 1 hr/day)",
    "sleep" = "Sleep (extra 1 hr/day)"
  )
)

rec_dat_hu$Model <-
  factor(rec_dat_hu$Model,
         ordered = TRUE,
         c("unhealthy", "healthy", "main analysis"))


my_cols <- c(viridis::viridis(n = 3)[2:1], "black")
```

Plotting: 
```{r}
p <- # DATA AND AESTHETICS
  ggplot(data = rec_dat_hu,
            aes(
              x = HR,
              y = BehaviourDet ,
              colour= Model,
              group = Model,
              label = label
            )) +
  # GEOMS
  geom_pointrange(position = position_dodge(0.6), aes(xmin = LowerCI, xmax = UpperCI), size = 1, shape = 18) +
  geom_text(
    size = 4.5,
    aes(x = 1.18, y = BehaviourDet, label = label),
    position = position_dodge(0.6),
    colour = "black", 
    fontface = "bold"
  ) +
  geom_vline(xintercept = 1, size = 0.75) +

  # SCALES
  scale_x_continuous(trans = "log10", breaks = c(0.9, 0.95, 1, 1.05)) +
  scale_color_manual(values = my_cols, guide = guide_legend(reverse = TRUE)) +
 # scale_shape_manual(values = c(18, 20), guide = "none" ) +

  # CONSISTENT THEME 
  consistent_theme

## save plot to file----------------------------------------------------------------------------------------------
svg(
  "plots/thesis-healthy-unhealthy.svg",
  width = 10,
  height = 5
)
print(p)
dev.off()
```



# E values (manual)

Calculating: 
```{r}
rec_dat_basic <- rec_dat_nc[seq(1, 7, by =2), ]
rec_dat_basic$Model <- NULL
rec_dat_basic$Difference <- NULL
rec_dat_basic$EValue <- NA
rec_dat_basic$IntervalBound <- NA

for (i in 1:nrow(rec_dat_basic)){
  print(i)
  evals <- evalues.RR(est = rec_dat_basic$HR[i], lo = rec_dat_basic$LowerCI[i], hi = rec_dat_basic$UpperCI[i], true = 1)
  print(evals)
  rec_dat_basic$EValue[i] <- evals["E-values", "point"]
  if (rec_dat_basic$HR[i] < 1){
    rec_dat_basic$IntervalBound[i] <- evals["E-values", "upper"]
  }
  else {
   rec_dat_basic$IntervalBound[i] <- evals["E-values", "lower"]
  }
}
rec_dat_basic$EValDesc <- paste0(round_2_dp(rec_dat_basic$EValue), " (", round_2_dp(rec_dat_basic$IntervalBound), ")")
rec_dat_basic$full_label <- paste0(rec_dat_basic$label, "         ", rec_dat_basic$EValDesc)
rec_dat_basic <- rbind(data.frame("Behaviour" = " ",   "HR"= NA, "LowerCI" = NA, "UpperCI" = NA, "label" = NA,      "BehaviourDet" = " ",  "EValue" = NA, "IntervalBound" = NA,  "EValDesc" = NA, "full_label" = "HR (CI)                        E-Value (Bound)") , rec_dat_basic)
rec_dat_basic$Behaviour <-
  factor(rec_dat_basic$Behaviour, ordered = TRUE, levels = c(rot_list[[1]], " "))
rec_dat_basic$BehaviourDet <- plyr::revalue(
  rec_dat_basic$Behaviour,
  c(
    "MVPA" = "MVPA (extra 20 min/day)",
    "LIPA" = "LIPA (extra 1 hr/day)",
    "SB" = "SB (extra 1 hr/day)",
    "sleep" = "Sleep (extra 1 hr/day)", 
    " " = " "
  )
)

```

Plotting: 
```{r}
p <- # DATA AND AESTHETICS
  ggplot(data = rec_dat_basic,
            aes(
              x = HR,
              y = BehaviourDet,
              label = full_label
            )) +
  # GEOMS
  geom_pointrange(position = position_dodge(0.6), aes(xmin = LowerCI, xmax = UpperCI), size = 1, shape = 18) +
  geom_text(
    size = 4.5,
    aes(x = 1.15, y = BehaviourDet, label = full_label),
    position = position_dodge(0.6),
    colour = "black", 
    fontface = "bold", 
    hjust = 0) +
  geom_vline(xintercept = 1, size = 0.75) +

  # SCALES
  scale_x_continuous(trans = "log10", breaks = c(0.9, 0.95, 1, 1.05)) +

  # CONSISTENT THEME 
  consistent_theme

## save plot to file----------------------------------------------------------------------------------------------
svg(
  "plots/thesis-evals.svg",
  width = 10,
  height = 5
)
print(p)
dev.off()
```